### ISSUE TITLE
Use Twitter API to get status updates

### ISSUE THREAD

**Issue by jdblischak** [rstats-net-health/rstats-net-health#1]
Many services report status updates on Twitter, e.g.:

* [@githubstatus](https://twitter.com/githubstatus)
* [@traviscistatus](https://twitter.com/traviscistatus)
* [@gitlabstatus](https://twitter.com/gitlabstatus)

Thus a good first start would be to use the R package [rtweet](https://cran.r-project.org/package=rtweet) to download the latest status update from these accounts, and then determine if the status is good or bad.

From the demo of the user interface I made, here's an example of a good status:

<img width="1340" alt="screen shot 2018-10-30 at 11 20 52 pm" src="https://user-images.githubusercontent.com/1608317/47764215-95236800-dc9a-11e8-8b5c-7758de3f04d7.png">

And here's an example of a bad status:

<img width="1325" alt="screen shot 2018-10-30 at 11 22 12 pm" src="https://user-images.githubusercontent.com/1608317/47764238-a8cece80-dc9a-11e8-9f3d-1a4ec77f71fb.png">

**Comment by denironyx** [comment]
Okay, nice to know we have somewhere to start this project. 

I will download the tweet data for #gitlabstatus, #githubstatus and #traviscistatus 

That would be a nice place to start from.

**Comment by jdblischak** [comment]
Some feedback for commit 30653a2e30eaafbbb64d597b618391d357bcfbcb:

1. Exclude retweets
2. Avoid spaces in names of directories and files

As a next step, can you try creating some heuristics to determine if the status is good or bad? You can use the tweets you downloaded as example input data. The traviscistatus updates seem the easiest to get started since the second word in the tweet is informative. For example:

1. "[status] Resolved: " -> success
1. "[status] Monitoring: " -> warning
1. "[status] Investigating: " -> danger

I used "success", "warning", and "danger" because then we can easily map these results to the corresponding [Bootstrap alerts](https://getbootstrap.com/docs/3.3/components/#alerts).

**Comment by denironyx** [comment]
Feedback on my work. 

I have been able to clean the tweet to a reasonable precision.  However, I'm dropping all of the column except that of the text columns.  I realize, the other column might not be useful. 

Current, I'm reading about sentimentR and text minning analysis. 

I'm hopeful, that I can get something to help me analyze the tweets further.

**Comment by jdblischak** [comment]
@denironyx Here are some specific goals to work on before our next meeting. Please let me know if you need clarification on any of them.

1. Update the Twitter data for accounts githubstatus, traviscistatus, and gitlabstatus.
  * Only include tweets made by the accounts, i.e. don't include retweets, replies, or mentions made by other user accounts
  * Filter the data to only include information we need, e.g. the date of the tweet, the text content of the tweet, and any other columns you think that could be potentially useful
  * Limit the number of rows to the most recent 100 tweets
  * Commit the updated data files and scripts to GitHub
2. As I described [above](https://github.com/rstats-net-health/rstats-net-health/issues/1#issuecomment-435503161), try to analyze the travisci tweets.
  * Write a function that accepts the text of the tweet and returns `"success"`, `"warning"`, `"danger"`, or `NA_character_`. Only return `NA_character_` if the tweet is unable to be classified into one of the other 3 categories.
  * Commit a file that contains the function definition as well as some examples of running the function.
3. Practice GitHub Pull Requests
  * Read my [tutorial on Git and GitHub](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1004668)
  * Follow the instructions to send a Pull Request to [jdblischak/git-for-science](https://github.com/jdblischak/git-for-science)

**Comment by denironyx** [comment]
Hi @jdblischak , I just commit some of the things you wanted me to work on. 

1. I have been able to update the data from accounts githubstatus, traviscistatus, and gitlabstatus.

- Collected only tweets that was made by the accounts. This was a bit tricky because, the userTimeline function of the twitteR package, was truncating some words from each tweet.  It was a big issue at first and I had to look into the documentation of both twitteR and rwteet packages an finally I found a way around it. The get_user_timeline function of rwteet did the job.  The only problem with this is that, it takes both tweets by the accounts and replies.  I had to make use the complete.cases logic to go about it. 
- It's about the same time to collect data of 200 tweets and 100. So, I collected for the most recent 200 tweets. But if you want me to remove the rest, it won't be a big deal. 

2. The truth, I still can't make any sense of it yet. I'm however, still taking a continua look at it. 

3. I have practice github pull requests.

**Comment by jdblischak** [comment]
> I have been able to update the data from accounts githubstatus, traviscistatus, and gitlabstatus.

@denironyx Great!

> Collected only tweets that was made by the accounts. This was a bit tricky because, the userTimeline function of the twitteR package, was truncating some words from each tweet. It was a big issue at first and I had to look into the documentation of both twitteR and rwteet packages an finally I found a way around it. The get_user_timeline function of rwteet did the job. The only problem with this is that, it takes both tweets by the accounts and replies. I had to make use the complete.cases logic to go about it.

I like your approach. Using `rtweet::get_timeline()` to download the tweets and then filtering based on `reply_to_user_id` to remove replies seems like a good strategy.

> It's about the same time to collect data of 200 tweets and 100. So, I collected for the most recent 200 tweets. But if you want me to remove the rest, it won't be a big deal.

I suggested a limit of 100 to keep the data files that we commit to GitHub small, not for speed. 200 lines is fine though.

> The truth, I still can't make any sense of it yet. I'm however, still taking a continua look at it.

I started the function and sent Pull Request #4. Please read this over and let me know if it is more clear what I'm requesting. One issue is that I had not realized that some of the tweets start with "Identified", so I also included that situation in the tests of the proposed functin.

> I have practice github pull requests.

OK. Please fork this repository to your account and try to send future updates via Pull Requests.

**Comment by jdblischak** [comment]
@denironyx Great chatting with you today! A quick summary of the action items from our meeting:

- [x] Merge Pull Requests (John)
- [x] Fork repository to personal account (Dennis)
- [x] Finish function `get_status_travisci()` (Dennis)
- [x] Send Pull Request with updated function (Dennis)

Please post here if you run into any issues.

**Comment by denironyx** [comment]
@jdblischak I have pushed the updated function the [github repo](https://github.com/rstats-net-health/rstats-net-health).

**Comment by jdblischak** [comment]
Great. So here is your function:

https://github.com/rstats-net-health/rstats-net-health/blob/1c07f3d482d6b683ff3748ad0f3b53538fdb0a3e/travisci.R#L14-L25

However, looking at the tests at the bottom of the file, the function fails most of them (the tests should all return `TRUE`). 

Let's look at the first test. To pass, the function needs to detect the presence of the word "Resolved" in the full string "[status] Resolved: This incident has been resolved.".

https://github.com/rstats-net-health/rstats-net-health/blob/1c07f3d482d6b683ff3748ad0f3b53538fdb0a3e/travisci.R#L32-L33

Have you ever done string pattern matching before? In base R, have a look at the function `grepl`. An alternative would be to use the function `str_detect` from the package [stringr](https://stringr.tidyverse.org/).

**Comment by jdblischak** [comment]
Resolved by PR #8
